[package]
name = "excursion"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
bytes = "1"
clap = "4.5.4"
expanduser = "1.2"
#path-absolutize = "3.1.1"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.4"
unix_mode = "0.1.4"
