;;; -*- lexical-binding: t; -*-

(require 'excursion)

(excursion--gen-tests
 ;; TODO: consider expand-file-name here
 excursion-expand-file-name
 ((("foo" "bar") "/excursion:electron:/home/mas/excursion/bar/foo")
  (("/foo" "bar") "/excursion:electron:/foo")
  (("~/foo" "~ms") "/excursion:electron:/home/mas/foo")
  (("~/foo" "bar") "/excursion:electron:/home/mas/foo")
  (("~foo" "bar") "/excursion:electron:/home/mas/excursion/bar/~foo")
  (("~baz" "bar") "/excursion:electron:/home/mas/excursion/bar/~baz")
  (("~/foo" "bar") "/excursion:electron:/home/mas/foo")
  (("foo" "~bar") "/excursion:electron:/home/mas/excursion/~bar/foo")
  (("/foo" "~bar") "/excursion:electron:/foo")
  (("~/foo" "~bar") "/excursion:electron:/home/mas/foo")
  (("~foo" "~bar") "/excursion:electron:/home/mas/excursion/~bar/~foo")
  (("~baz" "~/bar") "/excursion:electron:/home/mas/bar/~baz")
  (("~mas" "~bar") "/excursion:electron:/home/mas")
  (("~/foo" "~bar") "/excursion:electron:/home/mas/foo")
  (("foo" "~/bar") "/excursion:electron:/home/mas/bar/foo")
  (("/foo" "~/bar") "/excursion:electron:/foo")
  (("~/foo" "~/bar") "/excursion:electron:/home/mas/foo")
  (("~foo" "~/bar") "/excursion:electron:/home/mas/bar/~foo")
  (("~baz" "~/bar") "/excursion:electron:/home/mas/bar/~baz")
  (("~mas" "~/bar") "/excursion:electron:/home/mas")
  (("~/foo" "~/bar") "/excursion:electron:/home/mas/foo")
  (("foo" "/bar") "/excursion:electron:/bar/foo")
  (("/foo" "/bar") "/excursion:electron:/foo")
  (("~/foo" "/bar") "/excursion:electron:/home/mas/foo")
  (("~foo" "/bar") "/excursion:electron:/bar/~foo")
  (("~mas" "/bar") "/excursion:electron:/home/mas")
  (("~baz" "/bar") "/excursion:electron:/bar/~baz")
  (("~/foo" "~mas") "/excursion:electron:/home/mas/foo")
  (("foo" "~mas") "/excursion:electron:/home/mas/foo")
  (("/foo" "~mas") "/excursion:electron:/foo")
  (("~/foo" "~mas") "/excursion:electron:/home/mas/foo")
  (("~foo" "~mas") "/excursion:electron:/home/mas/~foo")
  (("~mas" "~mas") "/excursion:electron:/home/mas")
  (("~baz" "~mas") "/excursion:electron:/home/mas/~baz")
  (("~/foo" "~mas") "/excursion:electron:/home/mas/foo")
  (("~/foo" "~mas") "/excursion:electron:/home/mas/foo")
  (("foo" "~ms") "/excursion:electron:/home/mas/excursion/~ms/foo")
  (("/foo" "~ms") "/excursion:electron:/foo")
  (("~/foo" "~ms") "/excursion:electron:/home/mas/foo")
  (("~foo" "~ms") "/excursion:electron:/home/mas/excursion/~ms/~foo")
  (("~mas" "~ms") "/excursion:electron:/home/mas")
  (("~baz" "~ms") "/excursion:electron:/home/mas/excursion/~ms/~baz")
  (("foo" "") "/excursion:electron:/home/mas/excursion/foo")
  (("foo" nil) "/excursion:electron:/home/mas/excursion/foo")
  (("~/foo" nil) "/excursion:electron:/home/mas/foo")
  (("/foo" nil) "/excursion:electron:/foo")
  (("~foo" nil) "/excursion:electron:/home/mas/excursion/~foo")
  (("~mas" nil) "/excursion:electron:/home/mas"))
 :bindings ((default-directory "/excursion:electron:/home/mas/excursion/")))

(provide 'expand-file-name-test)
